
services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - httpbin
      - whoami

  httpbin:
    image: kennethreitz/httpbin
    expose:
      - "80"

  whoami:
    image: traefik/whoami
    expose:
      - "80"
